version: "3" # 도커 컴포즈 버전

services:
  # 이 곳에 실행하려는 컨테이너들을 정의

  react-app:
    # 컨테이너 이름
    build:
      context: .
      dockerfile: Dockerfile.prod
      # npm run build시 환경 변수 참조가 안되어 args로 전달하고, Dockerfile에서 변수로 사용한다.
      args:
        - REACT_APP_NAME=sangwoo
        - REACT_APP_TITLE=miya-prod
        - REACT_APP_TEST_VALUE=TEST_TEXT
    ports:
      - "9000:80"
